### ISSUE TITLE
Update inputs for simplified package install

### ISSUE THREAD

**Issue by MSP-Greg** [msys2/setup-msys2#165]
I'd like to propose adding two inputs, which I think would make the UX a bit better.

Borrowing two samples from the README:

```yaml
  steps:
  - uses: msys2/setup-msys2@v2
    with:
      update: true
      install: >-
        base-devel
        git
```

```yaml
  strategy:
    matrix:
      include:
        - { sys: mingw64, env: x86_64 }
        - { sys: mingw32, env: i686 }
        - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
        - { sys: clang64, env: clang-x86_64 } # Experimental!
  steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install: mingw-w64-${{matrix.env}}-toolchain
```

Let's combine them and add another package:

```yaml
  strategy:
    matrix:
      include:
        - { sys: mingw64, env: x86_64 }
        - { sys: mingw32, env: i686 }
        - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
        - { sys: clang64, env: clang-x86_64 } # Experimental!
  steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install: mingw-w64-${{matrix.env}}-toolchain mingw-w64-${{matrix.env}}-openssl base-devel git
```

Now, rewriting the above and adding `install-msys` and `install-mingw` inputs:

```yaml
  strategy:
    matrix:
      sys: [mingw64, mingw32, ucrt64, clang64]
  steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install-msys: base-devel git
        install-mingw: openssl toolchain
```

I think the workflow is much simpler with the additional inputs.  It's also easier for non-Windows users to get an idea of what it's doing.  Since the `sys` input defines what the package prefix is, we should have the action handle it, not the user.

Not sure if anyone is interested, or whether `install-msys` and `install-mingw` are good input choices.  If there's interest, I could work on a PR...
