### ISSUE TITLE
using latest rocksdb

### ISSUE THREAD

**Issue by leejw51crypto** [msys2/setup-msys2#220]
installed rocksdb like this, but in gorocksdb doesn't compile, because rocksdb is old version.

```
  windows-rocksdb-x86_64:    
    runs-on: windows-latest
    environment: release    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install:  mingw-w64-x86_64-rocksdb  

```
