### ISSUE TITLE
How to pass flags to pacboy?

### ISSUE THREAD

**Issue by txtsd** [msys2/setup-msys2#231]
```yml
  strategy:
    fail-fast: false
    matrix:
      sys: [ MINGW64, MINGW32, UCRT64, CLANG64 ]
  steps:
  - uses: msys2/setup-msys2@v2
    with:
      msystem: ${{matrix.sys}}
      install: >-
        git
        base-devel
      pacboy: >-
        openssl:p
```
In this example, what if I wanted to invoke pacboy as such: `pacboy --noconfirm -S --needed --cachedir $(cygpath "${{ github.workspace }}/${{ matrix.msystem }}")`

**Comment by MehdiChinoune** [comment]
> ```yaml
>   strategy:
>     fail-fast: false
>     matrix:
>       sys: [ MINGW64, MINGW32, UCRT64, CLANG64 ]
>   steps:
>   - uses: msys2/setup-msys2@v2
>     with:
>       msystem: ${{matrix.sys}}
>       install: >-
>         git
>         base-devel
>       pacboy: >-
>         openssl:p
> ```
> 
> In this example, what if I wanted to invoke pacboy as such: `pacboy --noconfirm -S --needed --cachedir $(cygpath "${{ github.workspace }}/${{ matrix.msystem }}")`

if you use setup-msys2 to install then you could just use `cache: true` to cache packages. There is no need to pass `--cachedir` to pacboy.

**Comment by txtsd** [comment]
Use `cache: true` where? I can't find any documentation for it.

**Comment by MehdiChinoune** [comment]
> Use `cache: true` where? I can't find any documentation for it.

Sorry, caching is enabled by default and there is no option for it https://github.com/msys2/setup-msys2#setup-msys2

**Comment by eine** [comment]
@txtsd see https://github.com/msys2/setup-msys2/blob/main/main.js#L316. The content of field `pacboy` is appended to `pacboy --noconfirm -S --needed`. Therefore, the following should work:

```yml
  strategy:
    fail-fast: false
    matrix:
      sys: [ MINGW64, MINGW32, UCRT64, CLANG64 ]
  steps:
  - uses: msys2/setup-msys2@v2
    with:
      msystem: ${{matrix.sys}}
      install: >-
        git
        base-devel
      pacboy: >-
        --cachedir "$(cygpath '${{ github.workspace }}/${{ matrix.msystem }}')"
        openssl:p
```
