### ISSUE TITLE
$PATH not icluded

### ISSUE THREAD

**Issue by Andrey-Shypko** [msys2/setup-msys2#232]
win10 not included User $PATH. System $PATH OK
win7 not included User $PATH and System $PATH

**Comment by hasufell** [comment]
Same here. All the tools that are available via PATH variable in the stock github windows machines stopped working.

**Comment by Biswa96** [comment]
Please explain the issue. How to reproduce it? What errors did you see? etc.

**Comment by hasufell** [comment]
```yml
  test:
    name: test
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
      - run: cabal --version
```

`cabal` is pre-installed on all windows runners. It doesn't work in msys2 shell.

**Comment by hasufell** [comment]
https://github.com/Maximus5/ConEmu/issues/1185#issuecomment-396570420

**Comment by Biswa96** [comment]
In GitHub Actions, that will be

```yml
      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
```
