### ISSUE TITLE
'location' not honored?

### ISSUE THREAD

**Issue by Lord-Kamina** [msys2/setup-msys2#288]
Hi. I've been using this action for a while, with very good results.
However, in a recent workflow I needed to patch a header and am having issues due to a "file not found" error.

I'm breaking my head over this, and with debug mode I noticed that msys is being installed to a random temp directory, despite my explicitly specifying a location.

Is this a known issue? Am I doing something wrong? Did something change that made a previous behavior break?

My workflow has 
```yaml

      - name: Install MSYS2.
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          location: ${{ github.workspace }}
          install: >-
            #A bunch of packages...
```

But, after erroring out and making a crude log to understand what is goin on, I see this:

```yaml
      - name: Check folders
        shell: bash
        run: |
          touch ${{ env.workpath }}/log.log
          pwd >> ${{ env.workpath }}/log.log
          ls -l ./ >> ${{ env.workpath }}/log.log
          ls -l ../ >> ${{ env.workpath }}/log.log
          ls -l ../.. >> ${{ env.workpath }}/log.log
```

Outputs:

> /d/a/gdb-win/gdb-win
> total 38
> -rw-r--r-- 1 runneradmin 197121 35823 Mar 14 17:27 LICENSE
> -rw-r--r-- 1 runneradmin 197121   494 Mar 14 17:27 enable-gmp-static.diff
> -rw-r--r-- 1 runneradmin 197121    21 Mar 14 17:27 log.log
> total 4
> drwxr-xr-x 1 runneradmin 197121 0 Mar 14 17:27 gdb-win
> total 4
> drwxr-xr-x 1 runneradmin 197121 0 Mar 14 17:25 _PipelineMapping
> drwxr-xr-x 1 runneradmin 197121 0 Mar 14 17:25 _actions
> drwxr-xr-x 1 runneradmin 197121 0 Mar 14 17:27 _temp
> drwxr-xr-x 1 runneradmin 197121 0 Mar 14 17:25 gdb-win

EDIT: Most importantly, the GA debug output says:

```
  shell: D:\a\_temp\setup-msys2\msys2.CMD {0}
  env:
    workpath: D:/a/gdb-win/gdb-win
    MSYSTEM: MINGW64
```
