### ISSUE TITLE
New installer hangs on clangarm64

### ISSUE THREAD

**Issue by jeroen** [msys2/setup-msys2#358]
See: https://github.com/r-windows/r-devel/actions/runs/7523495967/job/20476942849

```
Run msys2/setup-msys2@v2
Downloading MSYS2...
Extracting MSYS2...
Disable Key Refresh...
Restoring package cache...
Starting MSYS2 for the first time...
Disable CheckSpace...
Installing additional packages through pacman...
Saving package cache...
  C:\Windows\system32\cmd.exe /D /S /C C:\actions-runner\_work\_temp\setup-msys2\msys2.cmd -c "'paccache' '-r' '-f' '-u' '-k0'"
  Error: The operation was canceled.
```

I tried wiping the GHA caches, rebooting my runner, but it keeps hanging.

**Comment by jeroen** [comment]
FWIW, I run this job every day and it started specifically after https://github.com/msys2/setup-msys2/commit/280250c89e1fa7073887223180750f7a4133b20c. A workaround is to set `cache: false` like so:

```yml
      - uses: msys2/setup-msys2@v2
        timeout-minutes: 15
        with:
          msystem: ${{ matrix.msystem }}
          install: git patch make unzip pactoys
          cache: false
```
