### ISSUE TITLE
Error starting bash

### ISSUE THREAD

**Issue by h-g-s** [msys2/setup-msys2#38]
Thanks for the very useful GHA !

I'm trying to use it, but when I call  msys2do   it seems that   bash is crashing,  is anyone experiencing this too ?   My github action is quite small and includes almost only setup-msys2, I'll post here  (pamac install is being called after since install apparently did not worked, but other commands that I call after also crash bash):

name: C/C++ CI

on: 
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: numworks/setup-msys2@v1
        with:
          update: true
      - name: start build
        run: msys2do pamac -S git base-devel gcc mingw-w64-x86_64-lapack mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-readline mingw-w64-x86_64-suitesparse mingw-w64-x86_64-metis --no-confirm

I got the following error:   

> Run msys2do pamac -S git base-devel gcc mingw-w64-x86_64-lapack mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-readline mingw-w64-x86_64-suitesparse mingw-w64-x86_64-metis --no-confirm
D:\a\cbc-binaries\cbc-binaries>setlocal
D:\a\cbc-binaries\cbc-binaries>IF NOT DEFINED MSYS2_PATH_TYPE set MSYS2_PATH_TYPE=strict 
D:\a\cbc-binaries\cbc-binaries>D:\a\_temp\msys\\msys64\usr\bin\bash.exe -ilc "cd $OLDPWD && pamac -S git base-devel gcc mingw-w64-x86_64-lapack mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-readline mingw-w64-x86_64-suitesparse mingw-w64-x86_64-metis --no-confirm" 
      0 [main] bash (6560) shared_info::initialize: size of shared memory region changed from 51128 to 40888

Anyone experiencing similar issue ?

**Comment by eine** [comment]
Hi @h-g-s! It seems that you are using `numworks/setup-msys2@v1`, instead of `msys2/setup-msys2@v1`. Just change that, and it should work. I suggest to use the following template:

```yml
name: C/C++ CI
on:
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v1
      with:
        update: true
        install: git base-devel gcc mingw-w64-x86_64-lapack mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-readline mingw-w64-x86_64-suitesparse mingw-w64-x86_64-metis
    - uses: actions/checkout@v2
```
