### ISSUE TITLE
Use case: build matrix for 32bit and 64 bit

### ISSUE THREAD

**Issue by lazka** [msys2/setup-msys2#40]
A common CI use case is building your project for 32bit and 64bit, which in the setup-msys2 case also means the package names passed to "install" are different, and then in bash depending on the build do something different maybe.

I'd like to see an example for this in the README.

**Comment by eine** [comment]
Hi @lazk! I have thought about that, but the issue is that there are too many possibilities and it can be overwhelming. The principle is really simple: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy

```yml
    strategy:
      fail-fast: false
      max-parallel: N
      matrix:
        OBJECT/STRUCT_OR_LIST_OF_OBJECTS/STRUCTS
```

So, the most basic syntax is the one used in https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml#L12-L18:

```yml
      matrix:
        include:
          - msystem: MINGW64
            msystem_lower: mingw64
            arch: x86_64
          - msystem: MINGW32
            msystem_lower: mingw32
            arch: i686
```

Where you use the values as `${{ matrix.msystem }}`, `${{ matrix.msystem_lower }}` or `${{ matrix.arch }}`.

It can be rewritten as follows:

```yml
      matrix:
        task: [
          { msystem: MINGW64, msystem_lower: mingw64, arch: x86_64 },
          { msystem: MINGW32, msystem_lower: mingw32, arch: i686 }
        ]
```

This is equivalent, but values are used as `${{ matrix.task.msystem }}`, `${{ matrix.task.msystem_lower }}`, etc. This is used in https://github.com/ghdl/ghdl/blob/master/.github/workflows/push.yml#L60-L66.

At the same time, any of the parameters defined in the matrix can be used "anywhere", meaning any field of the YAML. Examples:

- Calling an Action: https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml#L30-L31 or https://github.com/msys2/setup-msys2/blob/master/.github/workflows/action.yml#L244
- Setting an envvar "manually": https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml#L35
- Setting "per job" envvars: https://github.com/ghdl/ghdl/blob/master/.github/workflows/push.yml#L68-L70
- Setting "per step" envvars: https://github.com/ghdl/ghdl/blob/master/.github/workflows/push.yml#L102
- Using params in shell snippets: https://github.com/ghdl/ghdl/blob/master/.github/workflows/push.yml#L86

As a result, I am not sure about putting all this in the README, because I don't want to duplicate GitHub Actions' docs. Instead, I think it would be desirable to add just some short comment that links to the docs and to https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml as a "living example".

BTW, `msystem: MINGW64, msystem_lower: mingw64` is clearly redundant an "annoying". It can be worked around as shown in https://github.com/umarcor/gtkwave/blob/ci-msys2/.github/workflows/build.yml#L46, but it would be desirable if either lowercase or uppercase values were accepted. Is it possible?

That last workflow is also interesting because the same tool is tested/built on MINGW64/MINGW32 and with gtk2/gtk3, i.e. four jobs are generated from the matrix: https://github.com/umarcor/gtkwave/blob/ci-msys2/.github/workflows/build.yml#L16-L20
