### ISSUE TITLE
Python3_ROOT_DIR is not set by setup-msys2

### ISSUE THREAD

**Issue by Paebbels** [msys2/setup-msys2#476]
GitHub Action runners (and I think also in combination with `setup-python` if the Python version is changed), set the `Python3_ROOT_DIR` environment variable. When running code inside a MSYS2 environment, this variable is not set.

My usecase is for checking if my platform dependent wheels are installing all files correctly. Therefore I need to know where the `site-packages` directory is located for the currently active Python version.

In case of MSYS2 environments (MinGW64 and UCRT64 in my cases), it's only a single version (currently 3.12), but the directory prefix is different per environment.

An can assemble that variable myself via `MSYSTEM_PREFIX`, but it would be nice for portable code on GitHub Action runners to also provide this variable from MSYS2.

```bash
PYTHON_SITE_PACKAGEs="$MSYSTEM_PREFIX/lib/python$(python --version | sed -E 's/Python ([0-9]+\.[0-9]+)\.[0-9]+/\1/')/site-packages"
```
This extracts the currently installed Python version number:  
```bash
python --version | sed -E 's/Python ([0-9]+\.[0-9]+)\.[0-9]+/\1/'
```

**Comment by lazka** [comment]
What about just asking Python instead?

```console
$ python -c "import sysconfig; print(sysconfig.get_path('platlib'))"
C:/msys64/clang64/lib/python3.12/site-packages
$ python -c "import sysconfig; print(sysconfig.get_python_version())"
3.12
```

That should work across all platforms.

**Comment by Paebbels** [comment]
Oh, I didn't know about `sysconfig.get_path('platlib')`. That's nice.

------------
I found two more issues with my proposed idea.

1. While `setup-python` knows what's installing, setup-msys2 would need to check the `install` or `pacboy` parameters and search for `python` and/or any related package using python as a dependency.  
   &rarr; that's asking for to much and impracticable
2. `setup-python` switches environment variables between pre-installed Python versions on disk. More over, as these variants aren't installed in `C:\Program Files\`, but as standalone installations, the predefined variable `Python3_ROOT_DIR` behaves similar to `MSYSTEM_PREFIX`.


By accessing the `msys2-location` output of the `setup-msys2` step, I was able to solve the problem.
   ```yaml
   jobs:
     Test:
       steps:
         - name: '🟦 Setup MSYS2 for ${{ inputs.runtime }}'
           id: msys2
           uses: msys2/setup-msys2@v2
           if: inputs.runtime != ''
           with:
             msystem: ${{ inputs.runtime }}
             update: true
             pacboy: 'python:p python-pip:p python-wheel:p'
   ```
   ```bash
   # Ubuntu
   tree ${Python3_ROOT_DIR}/lib/python3.*/site-packages/pyGHDL -I __pycache__

   # MSYS2
   tree "${{ steps.msys2.outputs.msys2-location }}${MSYSTEM_PREFIX}/lib/python$(python --version | sed -E 's/Python ([0-9]+\.[0-9]+)\.[0-9]+/\1/')/site-packages/pyGHDL" -I __pycache__
   ```
