### ISSUE TITLE
C compiler cannot create executables when using `CLANGARM64`

### ISSUE THREAD

**Issue by Joseph-Edwards** [msys2/setup-msys2#490]
## Summarry

I am adding a workflow job that compiles some C code on windows using msys2 with `autotools`. When I specify `msystem` to be `MINGW64`, `MINGW32`, `UCRT64` or `CLANG64` everything works fine. However, when I specify `msystem` to be `CLANGARM64`, I get an error when running `./configure` which says "C compiler cannot create executables".

## MRE
Inside `.github/workflows/mre.yml`
```yml
name: test
on: workflow_dispatch

jobs:
  msys:
    defaults:
      run:
        shell: msys2 {
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: CLANGARM64
          pacboy: toolchain autotools
      - uses: actions/checkout@v4
      - name: Configure . . .
        run: autoreconf -if && ./configure
```

## Expected behaviour

Everything to pass, as is the case when changing `CLANGARM64` to one of the other systems.

## Additional info
Please see [config.log]((https://github.com/user-attachments/files/19776916/config.log)) for the detailed log, and [this action](https://github.com/Joseph-Edwards/edge-addition-planarity-suite/actions/runs/14492006444/job/40650396013) for the place where this error occured.
