### ISSUE TITLE
Provide a way to cache the installation

### ISSUE THREAD

**Issue by ComFreek** [msys2/setup-msys2#50]
I currently have the workflow file below. Now I am still fiddling with it and whenever I add or change a step that is even unrelated to the `msys2/setup-msys2` step, in the next run this action will still redownload and reinstall all packages.

```
name: Build Binaries and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  windows-build: 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - uses: msys2/setup-msys2@v1
      with:
        msystem: MINGW64
        update: true
        cache: true
        install: "git diffutils mingw-w64-x86_64-clang make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-mesa mingw-w64-x86_64-openexr mingw-w64-x86_64-intel-tbb mingw-w64-x86_64-glm mingw-w64-x86_64-glew mingw-w64-x86_64-dbus patch mingw-w64-x86_64-openvdb"
```
