### ISSUE TITLE
install fails on windows-11-arm runner

### ISSUE THREAD

**Issue by robtaylor** [msys2/setup-msys2#516]
```
   - name: Install MSYS2 dependencies
      uses: msys2/setup-msys2@v2
      if: contains(matrix.os, 'windows')
      with:
        update: false
        release: false
        cache: true
        install: |
          git
        pacboy: |
          toolchain
```

Fails with:
```
Run msys2/setup-msys2@v2
  with:
    update: false
    release: false
    cache: true
    install: autotools
  git
    pacboy: toolchain

  
  
    msystem: MINGW64
    path-type: minimal
    location: RUNNER_TEMP
    platform-check-severity: fatal
Restoring package cache...
  Cache restore for msys[2](https://github.com/ChipFlow/Xyce-build/actions/runs/15756778839/job/44413870974#step:5:2)-pkgs-upd:false-conf:d84f6[3](https://github.com/ChipFlow/Xyce-build/actions/runs/15756778839/job/44413870974#step:5:3)62, got undefined
  Cache restore for msys2-pkgs-upd:false-conf:d8[4](https://github.com/ChipFlow/Xyce-build/actions/runs/15756778839/job/44413870974#step:5:4)f6362, got undefined
Starting MSYS2 for the first time...
  C:\Windows\system32\cmd.exe /D /S /C C:\a\_temp\setup-msys2\msys2.cmd -c "'uname' '-a'"
  The system cannot find the path specified.
  Error: The process 'C:\Windows\system32\cmd.exe' failed with exit code 1
```

**Comment by mmuetzel** [comment]
Overall, a skeleton workflow could look like this:
```
name: MSYS2 on ARM
on:
  push:

jobs:

  msys2-arm:
    runs-on: windows-11-arm

    name: MSYS2 (CLANGARM64)

    defaults:
      run:
        # Use MSYS2 as default shell
        shell: msys2 {0}

    steps:

      - name: install MSYS2 build environment
        uses: msys2/setup-msys2@v2
        with:
          update: true
          release: true
          msystem: CLANGARM64
          install: >-
            base-devel
          pacboy: >-
            cc:p

      - name: checkout repository
        uses: actions/checkout@v6

      - name: configure
        env:
          CC: clang
          CXX: clang++
        run: |
          [your configure steps]
       
      - name: build
        run: |
          [your build steps]
```
