### ISSUE TITLE
Save package cache as a post build step

### ISSUE THREAD

**Issue by jtanx** [msys2/setup-msys2#92]
This action is pretty neat, but one thing that would be nice is if saving the package cache could be deferred until after the build is done.

This would be ideal because I have a build script that installs many dependencies (and where it's not really practical to list them out directly in the workflows yml), so it would be nice if it cached those packages too. Not entirely sure if this is possible, although I see actions/cache does it as a post build step.

**Comment by lazka** [comment]
Sounds good.

I wonder why it's not practical to list them for you?

**Comment by jtanx** [comment]
There's a lot of packages to install, plus I also use the same build script outside of CI for manual invocations, so it would be nice to not have to list out the packages twice but have it work in both cases

**Comment by eine** [comment]
My concern with this request is that I use the resulting MSYS2 environment both for building and for testing a package. Hence, the package is installed before running the tests, but I don't want that to remain in the cache. Also, I don't think it's reasonable to keep uninstalling undesired packages. Therefore, I would propose users defining when to do the caching through an specific step. From a technical point of view, we can distribute two Actions or entrypoints:

```yml
  steps:

  - uses: msys2/setup-msys2@v2

  - run: install your deps here

  - run: do something else

  - uses: msys2/setup-msys2/cache@v2

  - run: install things which are not to be kept

  - run: test whatever
```

**Comment by eine** [comment]
> There's a lot of packages to install, plus I also use the same build script outside of CI for manual invocations, so it would be nice to not have to list out the packages twice but have it work in both cases

Note that you can define the list of packages in a file and have that file loaded and passed to setup-msys2.

**Comment by lazka** [comment]
> My concern with this request is that I use the resulting MSYS2 environment both for building and for testing a package. Hence, the package is installed before running the tests, but I don't want that to remain in the cache.

Note that only downloads end up in the cache, not things you install. So this is still an issue for our MSYS2 CI where we download random makedepends which we don't want to cache for the next run, but not for somewhat static sets of tasks.

We could also add an option to tell the action when to save the cache (in the common case the post-action would then just do nothing)

**Comment by jtanx** [comment]
> Note that you can define the list of packages in a file and have that file loaded and passed to setup-msys2.

That's good to know, I do multiarch builds though (both 32/64 bit), so having the post-build cache is definitely easier.

**Comment by txtsd** [comment]
This would be very helpful!

**Comment by MehdiChinoune** [comment]
I found a way to cache downloaded dependencies by using `--cachedir`:
```yaml
      - name: Cache/Restore packages
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ matrix.msystem }}
          key: ${{ matrix.msystem }}-${{ github.sha }}
          restore-keys: ${{ matrix.msystem }}-
      - name: Install prerequisites
        run: |
          pacboy -S --noconfirm \
            --cachedir $(cygpath "${{ github.workspace }}/${{ matrix.msystem }}") \
            cmake:p \
            ninja:p
```

**Comment by txtsd** [comment]
@MehdiChinoune 
What shell are you running `Install prerequisites` in? Because it doesn't work for me. Neither like this, nor with `shell: msys2 {0}`.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune What shell are you running `Install prerequisites` in? Because it doesn't work for me. Neither like this, nor with `shell: msys2 {0}`.

```yaml
    strategy:
      fail-fast: false
      matrix:
        msystem: [UCRT64, CLANG64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          release: false
          update: true
          install: pactoys
```
